/* ================================================================ the lists
   The exam asks "what are the five…" — from the Sep 24 exam notes. Each list
   becomes a "Name them" question (pick all n out of a spread of choices), a card,
   and a line on the Guide. `extra` are the wrong choices mixed in.             */
var LISTS = [
 {tp:"c4", id:"five-elements", q:"the five elements of the American political system", n:5,
  items:["Liberty","Equality","Democracy","Civic duty","Individual responsibility"],
  extra:["Prosperity","Security","Tradition","Patriotism"],
  e:"Liberty, equality, democracy, civic duty, individual responsibility — the exam’s “what are the five.”"},
 {tp:"c4", id:"three-differences", q:"the three major differences between countries", n:3,
  items:["Constitutional","Demographic","Cultural"],
  extra:["Economic","Geographic","Religious","Military"],
  e:"Countries differ constitutionally, demographically and culturally."},
 {tp:"c4", id:"culture-war", q:"the two sides of the culture war", n:2,
  items:["Orthodox","Progressive"],
  extra:["Liberal","Conservative","Traditionalist","Secular"],
  e:"Orthodox (morality and religion decisive) vs. progressive (personal freedom and social problems first)."},
 {tp:"c4", id:"trust", q:"the two events considered huge contributors to the decline of trust in government", n:2,
  items:["The Vietnam War","The Watergate scandal"],
  extra:["The Great Depression","World War II","The Iraq War","The 2008 financial crisis"],
  e:"Vietnam and Watergate."},
 {tp:"c5", id:"religion-clauses", q:"the two religion clauses of the First Amendment", n:2,
  items:["Establishment clause","Free exercise clause"],
  extra:["Supremacy clause","Due process clause","Equal protection clause","Elastic clause"],
  e:"“No law respecting an establishment of religion” (establishment) “or prohibiting the free exercise thereof” (free exercise)."},
 {tp:"c5", id:"fourteenth-clauses", q:"the two clauses of the Fourteenth Amendment from your notes (p. 100)", n:2,
  items:["Due process clause","Equal protection clause"],
  extra:["Establishment clause","Free exercise clause","Supremacy clause","Commerce clause"],
  e:"“Nor deprive any person of life, liberty, or property without due process of law” and “nor deny to any person within its jurisdiction the equal protection of the laws.”"},
 {tp:"c5", id:"unprotected", q:"the four kinds of speaking and writing that are not automatically protected", n:4,
  items:["Libel","Obscenity","Symbolic speech","False advertising"],
  extra:["Criticism of the president","Religious speech","Campaign speech","Editorials"],
  e:"Libel, obscenity, symbolic speech and false advertising."},
 {tp:"c5", id:"search", q:"the two ways a search can be reasonable", n:2,
  items:["With a warrant issued on probable cause","Incident to a lawful arrest"],
  extra:["With a neighbor’s consent","In daylight","For a serious enough crime","With a prosecutor’s note"],
  e:"A warrant on probable cause, or a search incident to a lawful arrest."},
 {tp:"c5", id:"lemon", q:"the three parts of the Lemon test", n:3,
  items:["A secular purpose","Neither advances nor inhibits religion","No excessive entanglement with religion"],
  extra:["Passed by two-thirds of Congress","Applies only to public schools","Approved by the president"],
  e:"Secular purpose; neither advances nor inhibits religion; no excessive entanglement."},
 {tp:"c5", id:"incorporation", q:"the three cases in the notes that applied the Bill of Rights to the states", n:3,
  items:["Gitlow v. New York (1925)","Palko v. Connecticut (1937)","McDonald v. Chicago (2010)"],
  extra:["Schenck v. United States (1919)","Texas v. Johnson (1989)","Lemon v. Kurtzman (1971)"],
  e:"Gitlow began incorporation, Palko made it selective, McDonald added the Second Amendment."},
 {tp:"c1", id:"five-views", q:"the five views of who governs", n:5,
  items:["Class (Marxist)","Power elite","Bureaucratic","Pluralist","Creedal passion"],
  extra:["Majoritarian","Federalist","Populist","Libertarian"],
  e:"Class (Marxist), power elite, bureaucratic, pluralist, creedal passion."},
 {tp:"c1", id:"four-types", q:"the four types of politics", n:4,
  items:["Majoritarian","Interest group","Client","Entrepreneurial"],
  extra:["Pluralist","Bureaucratic","Coalition","Partisan"],
  e:"Majoritarian, interest group, client, entrepreneurial — by who bears the costs and who gets the benefits."},
 {tp:"c2", id:"six-principles", q:"the six principles of the Constitution", n:6,
  items:["Popular sovereignty","Limited government","Separation of powers","Checks and balances","Federalism","Judicial review"],
  extra:["Direct democracy","Parliamentary supremacy","Unitary government"],
  e:"Popular sovereignty, limited government, separation of powers, checks and balances, federalism, judicial review."},
 {tp:"c2", id:"plans", q:"the two plans and the two compromises of the Convention", n:4,
  items:["Virginia Plan","New Jersey Plan","Great Compromise","Three-Fifths Compromise"],
  extra:["Hamilton Plan","Madison Compromise","Two-Thirds Compromise","Boston Plan"],
  e:"Virginia and New Jersey Plans; the Great and Three-Fifths Compromises."},
 {tp:"c2", id:"powers", q:"the three kinds of powers", n:3,
  items:["Enumerated","Reserved","Concurrent"],
  extra:["Absolute","Emergency","Sovereign","Royal"],
  e:"Enumerated (national), reserved (the states, Tenth Amendment), concurrent (both)."},
 {tp:"c3", id:"systems", q:"the three kinds of systems", n:3,
  items:["Unitary","Confederal","Federal"],
  extra:["Parliamentary","Presidential","Unicameral","Bicameral"],
  e:"Unitary, confederal, federal."},
 {tp:"c3", id:"cases", q:"the three landmark federalism cases", n:3,
  items:["Gibbons v. Ogden (1824)","Wabash (1886)","Arizona v. United States (2012)"],
  extra:["Gitlow v. New York (1925)","McDonald v. Chicago (2010)","Marbury v. Madison (1803)"],
  e:"Gibbons: Congress regulates interstate commerce. Wabash: states may not. Arizona: only the federal government regulates immigration."},
 {tp:"c3", id:"grants", q:"the three kinds of grants-in-aid", n:3,
  items:["Land grants","Categorical grants","Block grants"],
  extra:["Mandates","Conditions of aid","Devolution grants","Matching bonds"],
  e:"Land grants, categorical grants (specific purposes), block grants (broad purposes)."}
];
