/* ---- Exam 50 · chapter 1 · twelve topics, ten levels each ---- */
EX("c1","Issue",[
 XM("A conflict, real or apparent, between the interests, ideas, or beliefs of different citizens is:","an issue",["politics","power","legitimacy"],"That is Wilson’s definition of an issue."),
 XM("In Wilson’s terms, an issue is:","a conflict, real or apparent, between the interests, ideas, or beliefs of different citizens",["the activity, such as negotiation or force, by which a conflict is settled","the right to use power, as conferred by law or a constitution","a burden that people believe they must bear if a policy is adopted"],"The conflict itself is the issue."),
 XT("An issue can exist even when the conflict between citizens is only apparent, not real.",true,"True — “real or apparent.”"),
 XM("What is the difference between an issue and politics?","An issue is the conflict; politics is the activity that agitates or settles it",["An issue is the activity that settles things; politics is the conflict itself","They mean the same thing, since every conflict is already political","An issue is always economic in nature; politics is always about morals"],"Issue = the conflict. Politics = what people do about it."),
 XM("Neighbors disagree over whether their town should allow a new gas station. Before any meeting or vote, the disagreement is:","an issue",["politics","authority","a benefit"],"The conflict of interests is the issue."),
 XM("Residents only think a new park will hurt property values — it actually won’t — but they fight it anyway. Is this still an issue?","Yes — an issue can be real or merely apparent",["No — only conflicts that are real, not imagined, count as issues","No — a fight like this is politics, not an issue at all","Only if a court agrees that the harm to property is real"],"Wilson says real or apparent."),
 XM("Which three things can clash to create an issue, in Wilson’s definition?","Interests, ideas, or beliefs",["Laws, courts, and police","Parties, votes, and elections","Money, land, and labor"],"Interests, ideas, or beliefs of different citizens."),
 XM("Which statement about issues is NOT true?","An issue exists only after the government acts",["An issue can be real or apparent","An issue involves different citizens","Politics is how an issue is agitated or settled"],"The conflict comes first; government action is one way to settle it."),
 XM("Why does Wilson define an issue before he defines politics?","Politics is the activity by which an issue is agitated or settled, so it depends on there being an issue",["Issues matter more than politics, so the more important idea comes first in the chapter","Politics cannot involve force, so it needs a narrower term to be defined before it","Every issue is settled by the courts, so politics can only be defined after it"],"No conflict, nothing for politics to do."),
 XM("A city quietly bans skateboarding; no one objects or even notices. By Wilson’s definition, what is missing?","An issue — there is no conflict between citizens",["Power — the city could not enforce it","Authority — cities cannot pass bans","Legitimacy — the ban was not written down"],"Without a conflict of interests, ideas or beliefs, there is no issue.")]);

EX("c1","Politics",[
 XM("“The activity — negotiation, argument, discussion, application of force, persuasion, etc. — by which an issue is agitated or settled” defines:","politics",["an issue","authority","democracy"],"Politics."),
 XM("Politics, in Wilson’s definition, is:","the activity by which an issue is agitated or settled",["a conflict, real or apparent, between the interests of citizens","the right to use power, as conferred by law or a constitution","rule by the many, as Aristotle defined it"],"The activity — negotiation, argument, force, persuasion."),
 XT("In Wilson’s definition, the application of force can be part of politics.",true,"True — force is on his list, with negotiation and persuasion."),
 XM("Which pairing is correct?","Politics settles or agitates an issue; power is the ability to make others act",["Politics is the right to use power; power is a conflict between citizens","Politics and power mean the same thing: getting others to act as you intend","Politics is a burden people must bear; power is a benefit they expect to enjoy"],"Different ideas: the activity vs. the ability."),
 XM("Two council members trade favors and give speeches until they settle a zoning fight. What are they doing?","Politics",["Creating an issue","Exercising legitimacy","Practicing direct democracy"],"Negotiation and persuasion to settle an issue."),
 XM("Activists stage loud protests to make a quiet problem a public fight, without settling anything. Is that politics?","Yes — politics can agitate an issue, not only settle it",["No — in Wilson’s sense, politics only ever settles issues","No — protests are themselves issues, not the politics of them","Only if they win, since a losing protest is not politics"],"“Agitated or settled.”"),
 XM("Which list matches Wilson’s definition of politics?","Negotiation, argument, discussion, application of force, persuasion",["Voting, taxing, spending, appointing, judging, vetoing","Legislation, execution, adjudication, review, oversight","Liberty, equality, democracy, civic duty, responsibility"],"His exact list, “etc.” included."),
 XM("Which is NOT part of Wilson’s definition of politics?","It happens only inside government buildings",["It can involve persuasion and argument","It can involve the application of force","It agitates an issue or settles an issue"],"Politics is an activity, wherever it happens."),
 XM("Why does Wilson include force in a definition of politics?","Because issues are sometimes settled by coercion, not only by talk",["Because all politics is at bottom violent, whatever form it takes","Because force and authority are the same thing in Wilson’s terms","Because the Constitution says force is a lawful political tool"],"The definition describes how issues actually get settled."),
 XM("A student council settles a dress-code fight by a vote after weeks of debate. A dictator settles a similar fight by decree. By Wilson’s definition:","both are politics — the methods differ",["only the vote is politics","only the decree is politics","neither, since no one used persuasion"],"Negotiation and force both settle issues.")]);

EX("c1","Power",[
 XM("The ability of one person to get another person to act in accordance with the first person’s intentions is:","power",["authority","legitimacy","an issue"],"Power."),
 XM("Power means:","the ability to get another person to act in accordance with your intentions",["the right to use authority that the law has conferred on an office","political authority conferred by a state or national constitution","a conflict, real or apparent, between the beliefs of citizens"],"The ability — not the right."),
 XT("Power and authority mean the same thing.",false,"False — power is the ability; authority is the right to use it."),
 XM("What separates power from authority?","Power is the ability; authority is the right to use it",["Power is legal and authority is illegal, whoever holds them","Authority is always stronger than power, in every case","Power belongs only to governments; authority to individuals"],"Ability vs. right."),
 XM("A teacher gets students to finish homework by promising extra credit. What is she using?","Power — she gets them to act as she intends",["An issue — a conflict between her and her students","Legitimacy — authority conferred by the school’s rules","Direct democracy — the class decides for itself"],"Getting others to act as you intend is power."),
 XM("A bully gets classmates to hand over lunch money, though he has no right to it. He has:","power, but not authority",["authority, but not power","legitimacy","both power and authority"],"No right to use it — so no authority."),
 XM("In Wilson’s definition, whose intentions does power serve?","The first person’s — the one exercising it",["The majority’s — whoever has the most votes","The Constitution’s — the law behind the act","The courts’ — whoever settles the dispute"],"Getting another person to act in accordance with the first person’s intentions."),
 XM("Which statement about power is NOT true?","Power exists only when it is written into law",["Power can exist without authority","Power is the ability to make others act","A bully can have power"],"Legal grant makes it authority or legitimacy, not power."),
 XM("Why do the notes separate power from authority at all?","Because people can make others act without having any right to do so",["Because power and authority are opposites that never overlap","Because power is always illegal unless the law grants authority","Because the Framers banned power and allowed only authority"],"The ability and the right can come apart."),
 XM("A popular celebrity persuades millions to donate to a cause; a mayor orders a street closed. Which is the best judgment?","Both use power; only the mayor also has authority",["Only the celebrity uses power; the mayor has authority only","Only the mayor uses power; the celebrity has only influence","Neither uses power; both are simply exercising authority"],"Both get others to act; only one has the right conferred by office.")]);

EX("c1","Authority",[
 XM("The right to use power is:","authority",["power","an issue","a benefit"],"Authority."),
 XM("Authority means:","the right to use power",["the ability to make others act","a conflict between citizens","rule by the many"],"The right, not the ability."),
 XT("Authority is the right to use power.",true,"True."),
 XM("Which pairing is correct?","Power is the ability; authority is the right",["Power is the right; authority is the ability","Both mean the ability","Both mean a conflict"],"Ability vs. right."),
 XM("Drivers stop because a traffic officer, entitled to direct traffic, raises her hand. This is:","authority",["an issue","client politics","a confederation"],"She has the right to use power."),
 XM("A newly elected mayor has the legal right to set the budget, but the council ignores her and she cannot make them act. She has:","authority, but little power",["power, but no authority","neither","legitimacy only, without authority"],"The right without the ability."),
 XM("Which comes closest to Wilson’s idea that authority must be accepted as rightful?","People obey because they believe the officeholder is entitled to command",["People obey because they fear the force the officeholder can use","People obey because they are paid or rewarded for going along","People obey because the officeholder has raised an issue with them"],"Authority is the right to use power."),
 XM("Which statement about authority is NOT true?","Authority and power always go together",["Authority is the right to use power","Someone can have authority but little power","Legitimacy is authority conferred by law"],"They can come apart in either direction."),
 XM("Why does government need authority, not just power?","People obey more willingly when they believe the power is used by right",["Authority lets a government set the law aside whenever it chooses","Power by itself is illegal unless a court approves each use of it","The Constitution forbids power and permits only authority"],"Rightful power is steadier than raw force."),
 XM("A usurper takes power by force and keeps it for years. Critics say he still lacks something no army can give him. What?","Authority — a recognized right to rule",["Power — the ability to make people act as he wishes","An issue — a conflict between him and the citizens","Enumerated powers — duties listed in a constitution"],"He can make people act, but not make it rightful.")]);

EX("c1","Legitimacy",[
 XM("Political authority conferred by law or by a state or national constitution is:","legitimacy",["power","an issue","civic duty"],"Legitimacy."),
 XM("Legitimacy means:","political authority conferred by law or by a state or national constitution",["the ability of one person to make another act as the first intends","a conflict, real or apparent, between the interests of different citizens","a patterned and sustained way of thinking about how politics ought to work"],"Authority conferred by law or a constitution."),
 XT("For the Framers, a legitimate government required the consent of the governed.",true,"True — from the guide."),
 XM("How does legitimacy relate to authority?","Legitimacy is authority conferred by law or a constitution",["Legitimacy is power held without any authority behind it","Legitimacy and authority are opposites that never go together","Legitimacy is an issue that arises when authority is disputed"],"A particular source of authority."),
 XM("A president takes office after winning an election held under the constitution. His authority is:","legitimate",["illegitimate","only power","an issue"],"Conferred by law and the constitution."),
 XM("A general seizes the capital and most citizens refuse to accept his rule as lawful. What does his government lack?","Legitimacy",["Power","An issue","Force"],"He has power; he lacks authority conferred by law and consent."),
 XM("Where, in the notes, does legitimacy come from?","Law, or a state or national constitution",["The army, or the power to enforce the ruler’s will","Tradition alone, whatever the law or constitution says","Wealth, or the resources to reward those who obey"],"Conferred by law or a constitution."),
 XM("Which statement about legitimacy is NOT true?","A government is legitimate as long as it has enough force",["It is authority conferred by law or a constitution","The Framers tied it to consent of the governed","A usurper can have power without it"],"Force is power, not legitimacy."),
 XM("Why did the Framers insist on the consent of the governed?","Without consent, a government has power but no legitimate authority",["Consent made taxes unnecessary, since people would give freely","The king required consent before any colony could form a government","Consent guaranteed a direct democracy in which citizens voted on every law"],"Legitimacy rests on consent."),
 XM("A government follows its constitution to the letter, but most citizens no longer accept that constitution. Which is the best judgment by the notes?","Its legitimacy is weakening, because consent of the governed is slipping",["It is fully legitimate forever, because it follows its constitution","It has lost all its power, because power depends on popularity","It has become a direct democracy, because citizens now decide"],"Legal form plus consent — both matter.")]);

EX("c1","Democracy — Aristotle",[
 XM("Aristotle’s definition of democracy is:","the “rule of the many”",["the “rule of the few”","the “rule of the best”","the “rule of one”"],"Rule of the many."),
 XM("Wilson uses “democracy” to describe regimes that:","come as close as possible to Aristotle’s “rule of the many”",["are run by elected kings who answer to a council of nobles","have no written constitution and rely on custom instead","are run by trained experts chosen for their knowledge"],"As close as possible to rule of the many."),
 XT("Wilson uses “democracy” for regimes that come as close as possible to Aristotle’s “rule of the few.”",false,"False — the rule of the many."),
 XM("Which pairing is correct?","Democracy = rule of the many; aristocracy or oligarchy = rule of the few",["Democracy = rule of the few; aristocracy or oligarchy = rule of the many","Democracy = rule of one; aristocracy or oligarchy = rule of law","Democracy = rule of law; aristocracy or oligarchy = rule of the rich"],"The many vs. the few."),
 XM("A country where every adult citizen helps decide who governs comes closest to:","Aristotle’s “rule of the many”",["the power elite view","a unitary system","client politics"],"Many rule."),
 XM("A country holds elections, but only property owners — five percent of adults — may vote. It is closer to:","rule of the few",["rule of the many","direct democracy","pure democracy"],"Five percent is the few."),
 XM("Whose definition does Wilson borrow for democracy?","Aristotle’s",["Locke’s","Tocqueville’s","Madison’s"],"Aristotle: the rule of the many."),
 XM("Which statement is NOT true?","Wilson says no regime can be called a democracy unless it matches Aristotle exactly",["Democracy, in Wilson’s use, means Aristotle’s rule of the many","Wilson applies the word to regimes that come as close as possible","Representative democracy is one of the forms Wilson describes"],"“As close as possible,” not exactly."),
 XM("Why does Wilson say regimes that come “as close as possible” to the rule of the many?","Because in large nations the many cannot all rule directly",["Because Aristotle’s definition was wrong and needs softening","Because the Constitution forbids calling any regime a democracy","Because in every nation only a few people are allowed to vote"],"Representation brings a large nation close."),
 XM("Which judgment best fits the notes: is the United States a democracy?","Yes, in the sense of a representative democracy that comes close to rule of the many",["No — the word democracy can never apply to the United States","Yes — in the sense of a pure direct democracy where citizens vote on laws","No — by design it is rule of the few, not rule of the many"],"A republic — representative democracy.")]);

EX("c1","Direct vs. representative democracy",[
 XM("A government in which leaders make decisions by winning a competitive struggle for the popular vote is:","representative democracy",["direct or participatory democracy","a confederation","a unitary system"],"Representative democracy."),
 XM("Direct or participatory democracy is:","a government in which all or most citizens participate directly",["a government in which leaders win a competitive struggle for votes","a government in which the states hold sovereignty over the nation","a government in which judges make most important decisions"],"All or most citizens participate directly."),
 XT("In a representative democracy, leaders win a competitive struggle for the popular vote.",true,"True."),
 XM("What separates direct from representative democracy?","Who decides: the citizens themselves, or leaders they elect",["Whether the government has a written constitution or not","Whether there are states under the national government","Whether courts exist to settle disputes between citizens"],"Citizens decide vs. elected leaders decide."),
 XM("Every adult in a small New England town gathers and votes on the town budget. This is:","direct or participatory democracy",["representative democracy","a republic","the power elite view"],"Citizens participate directly."),
 XM("Voters in a state approve a tax by a ballot measure, while their legislature handles everything else. The ballot measure is:","a direct element inside a representative system",["pure representative democracy with no direct element","a confederation in which the states are sovereign","an enumerated power given to the national government"],"Citizens deciding directly on one question."),
 XM("In representative democracy, how do leaders earn the right to decide?","By winning a competitive struggle for the popular vote",["By inheriting office from a parent or relative","By appointment from the courts after a hearing","By passing an examination set by civil servants"],"Wilson’s wording."),
 XM("Which statement is NOT true?","The Framers designed a direct democracy",["Direct democracy means citizens participate directly","Representative democracy uses elections","The Framers feared fleeting passions"],"They designed a republic — representative."),
 XM("Why is representative democracy more practical for a large nation?","Millions of citizens cannot meet to decide every question themselves",["It needs no elections, which saves time and money","It removes all issues, since leaders agree on everything","It gives every important power to the states alone"],"Scale."),
 XM("A reformer wants every federal law decided by national online vote. Based on the Framers’ reasoning, what is the strongest objection?","Large issues might be decided by fleeting passions",["It would end federalism by removing the states","It would give the federal courts all the power","It would turn the nation into a confederation"],"Exactly the Framers’ worry about direct democracy.")]);

EX("c1","Why the Framers feared direct democracy",[
 XM("Many Framers believed direct democracy would lead to bad decisions because:","people often decide large issues on the basis of fleeting passions",["too few citizens could vote to make the results fair","the states would lose all their powers to the national majority","it would require a king to carry out the people’s decisions"],"Fleeting passions."),
 XM("“Fleeting passions,” in the Framers’ worry, means:","emotions of the moment that pass quickly",["long-held religious beliefs","written laws","the views of judges"],"Momentary feelings."),
 XT("Many Framers thought direct democracy would produce wise decisions because the people are always well informed.",false,"False — they feared fleeting passions."),
 XM("Which best contrasts the Framers’ view of the two democracies?","Direct risks passion-driven choices; representation filters them",["Direct is slower to act; representation is faster to act","Both are equally dangerous, so neither was preferred","Representation removes all issues; direct creates them"],"Representatives buy time to deliberate."),
 XM("After a frightening news story, a crowd votes that same day to ban something it later regrets. This illustrates:","the Framers’ fear of fleeting passions",["the power elite view of who governs","the enumerated powers of Congress","the devolution of power to the states"],"Passion deciding a large issue."),
 XM("A nation’s voters approve a sweeping war in a rush of anger, then turn against it months later. Which Framers’ concern does this best fit?","Large issues decided on fleeting passions",["Legislatures ignoring the people","Courts favoring the powerful","States overpowering the nation"],"Momentary anger, lasting consequences."),
 XM("On which kind of issues did the Framers most fear passion?","Large issues",["Local traffic rules","Private family matters","Court scheduling"],"“Decide large issues on the basis of fleeting passions.”"),
 XM("Which statement is NOT true of the Framers?","They wanted citizens to vote directly on every law",["They feared fleeting passions","They preferred representation","They wrote of a republican form of government"],"The opposite of their design."),
 XM("Why would a system of representation answer the Framers’ fear?","Representatives can deliberate and let passions cool before deciding",["Representatives never make mistakes, unlike ordinary citizens","Representation removes the need for any elections at all","Representation gives the states every power over the nation"],"Filtering passion through deliberation."),
 XM("Which modern feature would the Framers most likely approve, given their fear?","A waiting period and debate before a major law takes effect",["Instant national votes on every law by text message","Abolishing the Senate so the House acts alone and faster","Letting crowds at public meetings decide court cases"],"Cooling-off time answers fleeting passions.")]);

EX("c1","“Republican form of government”",[
 XM("Instead of “democracy,” the Constitution guarantees the states:","a republican form of government",["a direct form of democracy","a confederal form of union","a unitary form of government"],"By which the Framers meant representative democracy."),
 XM("By a “republic,” the Framers meant:","a government in which a system of representation operates",["a government with no constitution","rule by a king limited by law","a government where citizens vote on every law"],"Representation."),
 XT("The Constitution uses the word “democracy.”",false,"False — it does not; it speaks of a republican form of government."),
 XM("How does a republic, in the Framers’ sense, relate to democracy?","It is what we now call representative democracy",["It is the opposite of democracy, meaning rule by a few","It is what we now call direct or participatory democracy","It is a limited monarchy with an elected assembly"],"Republic = representative democracy."),
 XM("A country elects a legislature that makes laws for everyone. In the Framers’ language, this is:","a republic",["a direct democracy","a confederation","an aristocracy"],"A system of representation."),
 XM("A student says the U.S. “isn’t a democracy, it’s a republic.” By the notes, what is the best response?","It is both: a republic is what we call representative democracy",["She is right; a republic and a democracy are opposites","She is wrong; the U.S. is a direct democracy, not a republic","She is right; a republic is a kind of limited monarchy"],"The Framers’ “republic” = representative democracy."),
 XM("Which phrase does the Constitution use instead of “democracy”?","“Republican form of government”",["“Rule of the many”","“Democratic union”","“Popular sovereignty”"],"Its exact phrase."),
 XM("Which statement is NOT true?","The Framers’ republic meant citizens deciding every law directly",["The Constitution avoids using the word democracy","A republic, to the Framers, uses a system of representation","We would call the Framers’ republic a representative democracy"],"That would be direct democracy."),
 XM("Why might the Framers have avoided the word “democracy”?","To them it suggested direct rule by passionate majorities",["The word democracy was illegal to use in official documents in 1787","To them democracy meant monarchy with an elected council","Aristotle had forbidden the word, and the Framers followed him"],"Their fear of direct democracy."),
 XM("Which best captures the Framers’ design?","The people rule, but through representatives who filter passions",["The people rule nothing; elected officials decide everything","The people vote directly on every law, without representatives","The states rule the nation, and the people have no voice"],"A republic.")]);

EX("c1","The five views of who governs",[
 XL("five-views"),
 XM("The view that the wealthy — capitalists and other economic elites — determine most policies is the:","class (Marxist) view",["power elite view","pluralist view","creedal passion view"],"Wealth rules."),
 XT("The pluralist view holds that a single group of the wealthy controls most policy.",false,"False — pluralists see many competing groups; that description is the class view."),
 XM("What separates the class view from the power elite view?","The class view points to the wealthy; the power elite view to a group of business, military, labor and elected leaders",["They are the same view under two names, both pointing only to the richest families","The class view points to career bureaucrats; the power elite view to the wealthy alone","The power elite view points to morally impassioned elites; the class view to ordinary voters"],"Wealth vs. a broader leadership group."),
 XM("A writer argues that farmers, unions, businesses and churches all compete, and each wins sometimes. Which view?","Pluralist",["Power elite","Class","Bureaucratic"],"Many competing groups."),
 XM("A writer argues that career officials in federal agencies make policy whoever is elected. Which view?","Bureaucratic",["Pluralist","Creedal passion","Power elite"],"Appointed officials run things."),
 XM("The view that morally impassioned elites drive political change is the:","creedal passion view",["class view","bureaucratic view","pluralist view"],"Morals — e.g., reform movements."),
 XM("Which is NOT one of the five views?","The judicial view",["The pluralist view","The creedal passion view","The bureaucratic view"],"Class, power elite, bureaucratic, pluralist, creedal passion."),
 XM("Why do these five views disagree so much?","They disagree about who actually holds political power in America",["They disagree about what the text of the Constitution says","They disagree about how Aristotle defined democracy","They agree completely and differ only in their names"],"Five answers to “who governs?”"),
 XM("A new law passes after a moral crusade by a few passionate leaders, over the objection of big business. Which view does this case support, and which does it weaken?","Supports creedal passion; weakens the class view",["Supports class; weakens pluralist","Supports bureaucratic; weakens creedal passion","Supports power elite; weakens nothing"],"Morals beat money here.")]);

EX("c1","Courts and unpopular causes",[
 XM("According to Wilson, the preferred vehicles for the advocates of unpopular causes are:","the courts",["the political parties","Congress","state governors"],"The courts."),
 XM("The courts, Wilson says, are preferred by:","advocates of unpopular causes",["the majority party","large corporations only","state governors"],"Those who cannot win at the ballot box."),
 XT("National policy is increasingly being made by the actions of state governments.",true,"True — a line from the guide."),
 XM("Why might an unpopular cause choose a court over a legislature?","A judge rules on law and rights, not on popularity",["Courts count votes, so a small group can win there","Courts are elected every year and listen to minorities","Legislatures cannot pass laws on unpopular subjects"],"Majorities decide legislatures."),
 XM("A small group cannot win a vote in Congress for its cause. Where does Wilson say such advocates usually turn?","The courts",["The Electoral College","A constitutional convention","The Senate filibuster"],"Courts are the preferred vehicle."),
 XM("A cause loses in Congress but a few states adopt it and others copy them. Which line from the guide does this fit?","National policy is increasingly being made by the actions of state governments",["The courts are the preferred vehicles of the majority party, not of minorities","Only Congress makes national policy; the states merely carry it out","States have no role at all in making policy that others later copy"],"Policy spreading from the states."),
 XM("Which two venues does the guide name for policy outside Congress?","The courts, and the state governments",["The cabinet and the military","The churches and the schools","The parties and the press"],"Courts for unpopular causes; states increasingly for national policy."),
 XM("Which statement is NOT from the guide?","Congress is the preferred vehicle for unpopular causes",["Courts are preferred for unpopular causes","State governments increasingly make national policy","Issues can be settled outside Congress"],"The courts are."),
 XM("Why do courts suit unpopular causes in a representative democracy?","Representatives answer to majorities; judges answer to law",["Judges are chosen by the minority, so they favor it","Courts can raise taxes to fund unpopular causes","Courts act faster than elections, so causes win sooner"],"Majority rule vs. rule of law."),
 XM("A group loses every election but wins a string of court rulings. What is the best judgment about the notes’ claim?","It fits: courts are the preferred vehicle for unpopular causes",["It contradicts the claim, since courts follow elections","It shows courts are majoritarian, like Congress","It proves Congress is too weak to pass any laws"],"Exactly the pattern Wilson describes.")]);

EX("c1","The four types of politics",[
 XL("four-types"),
 XM("In Wilson’s terms, a benefit is:","any satisfaction, monetary or nonmonetary, that people believe they will enjoy if a policy is adopted",["a burden that people believe they must bear if a policy is adopted by government","money given by the national government to the states, with or without conditions","a conflict, real or apparent, between the interests, ideas, or beliefs of citizens"],"Benefit."),
 XT("A cost is a burden people believe they must bear if a policy is adopted.",true,"True."),
 XM("What separates client politics from entrepreneurial politics?","Client: concentrated benefits, distributed costs. Entrepreneurial: distributed benefits, concentrated costs",["They are the same type of politics, simply described from two different sides","Client: everyone benefits and everyone pays. Entrepreneurial: a few benefit, a few pay","Entrepreneurial: small groups benefit and small groups pay. Client: the exact reverse"],"Mirror images."),
 XM("A program nearly everyone pays for and nearly everyone benefits from is:","majoritarian politics",["client politics","interest group politics","entrepreneurial politics"],"Distributed and distributed."),
 XM("A subsidy for a small industry, paid by every taxpayer a little each, is:","client politics",["entrepreneurial politics","majoritarian politics","interest group politics"],"Concentrated benefits, distributed costs."),
 XM("A labor union and an industry fight over a rule that helps one and costs the other. This is:","interest group politics",["majoritarian politics","client politics","entrepreneurial politics"],"Concentrated and concentrated."),
 XM("Which is NOT one of the four types of politics?","Judicial politics",["Majoritarian","Client","Entrepreneurial"],"Majoritarian, interest group, client, entrepreneurial."),
 XM("Why does entrepreneurial politics need a “policy entrepreneur”?","The few who pay are organized and fight hard, while the many who benefit barely notice",["Because everyone benefits equally, so no one has any reason to act on it","Because the courts require a named entrepreneur for every new policy","Because the costs are spread so thin across the public that nobody notices"],"Someone must rally the diffuse majority."),
 XM("A clean-air rule helps the whole public but costs one industry heavily. Predict the politics.","Entrepreneurial: the industry fights hard; the diffuse public needs a champion to win",["Majoritarian: little conflict, since nearly everyone gains and pays","Client: the industry wins quietly, since the public pays little","Interest group: two organized sides bargain until one gives way"],"Distributed benefits, concentrated costs.")]);
