/* ---- Exam 50 · chapter 2 · twelve topics, ten levels each ---- */
EX("c2","The Constitutional Convention",[
 XM("Where and when was the Constitutional Convention held?","Philadelphia, 1787",["Boston, 1776","New York, 1789","Philadelphia, 1776"],"Philadelphia, 1787."),
 XM("The meeting in Philadelphia in 1787 that wrote the Constitution is the:","Constitutional Convention",["Continental Congress of 1776","Great Compromise","Articles of Confederation"],"The Constitutional Convention."),
 XT("The Constitutional Convention met in 1776, the same year as the Declaration of Independence.",false,"False — 1787."),
 XM("How do 1776 and 1787 differ in the story?","1776: independence declared; 1787: the Constitution written in Philadelphia",["1776: the Constitution written in Philadelphia; 1787: independence declared","1776: Shays’s Rebellion broke out; 1787: the Articles were adopted","1776: the Bill of Rights ratified; 1787: the Great Compromise rejected"],"Independence first, Constitution eleven years later."),
 XM("Delegates meet to replace a failing weak national framework with a new plan of government. Which event is this?","The Constitutional Convention of 1787",["The Declaration of Independence","Shays’s Rebellion","The ratification of the Bill of Rights"],"Philadelphia, 1787."),
 XM("A delegate complains the Convention is drafting a whole new government rather than just patching the old one. What is he contrasting?","The new Constitution with the Articles of Confederation",["The Declaration of Independence with the Bill of Rights","The Pennsylvania constitution with the Massachusetts one","The House of Representatives with the Senate"],"The Convention replaced the Articles."),
 XM("In counting representation for the House, the Constitution added to “the whole number of free persons”:","three-fifths of all other persons (enslaved people)",["all persons equally, whether free or enslaved","only white male property owners over twenty-one","one-half of all women and all enslaved people"],"The three-fifths clause."),
 XM("Which statement is NOT true?","The Convention met in Boston",["It met in Philadelphia","It met in 1787","It produced the Constitution"],"Philadelphia."),
 XM("Why did the three-fifths clause matter so much to the states?","It decided how many House seats — and how much power — each state would get",["It set the dates of federal elections in each of the states","It created the Senate and decided how senators were chosen","It ended slavery in the states that ratified the Constitution"],"Representation by population was power."),
 XM("Which is the best judgment of the three-fifths clause, as the guide presents it?","A compromise over representation that counted enslaved people as less than whole persons",["A guarantee of equal rights for every person the Constitution counted","A rule about how many senators each slave state would receive","A holdover from the Articles of Confederation that the Framers kept"],"It was about apportioning the House.")]);

EX("c2","Unalienable rights and consent",[
 XM("Unalienable rights are based on:","nature and Providence, not the whims or preferences of people",["the laws passed by Congress and the state legislatures","the will of the majority as expressed in elections","the king’s grant, recorded in each colony’s charter"],"Nature and Providence."),
 XM("Rights based on nature and Providence, which no one can take away, are:","unalienable rights",["enumerated powers","conditions of aid","civil rights"],"Unalienable rights."),
 XT("For the colonists, a legitimate government required the consent of the governed.",true,"True."),
 XM("What separates an unalienable right from a legal privilege?","An unalienable right comes from nature; a privilege is granted by people and can be taken back",["They are the same: both are granted by people and both can be taken back by them","A privilege comes from nature; an unalienable right is granted by the law and can be lost","Unalienable rights come from Congress; privileges come from the state governments"],"Source: nature and Providence vs. human grant."),
 XM("A new majority votes to take away a right. On the colonists’ view of unalienable rights, why may it not?","Those rights come from nature and Providence, not from people’s preferences",["Only the king may take rights away, and he has not done so","Rights can be changed only once every ten years by a convention","The courts granted those rights, so only the courts may remove them"],"No vote grants them."),
 XM("A king says his subjects’ liberties are gifts he may withdraw. How would the colonists answer?","Their rights are unalienable — from nature and Providence, not from the king",["He is right; liberties come from rulers and can be withdrawn","Only Parliament, not the king, may withdraw their liberties","Their rights come from the colonial assemblies, not the king"],"That was the heart of their argument."),
 XM("Many colonists believed men seek power because they are:","ambitious, greedy, and easily corrupted",["poor, frightened, and easily led","loyal, humble, and easily satisfied","naturally good and generous to others"],"Hence their distrust of power."),
 XM("Which statement is NOT part of the colonists’ thinking?","Rights are whatever the majority decides",["Rights come from nature and Providence","Men seek power out of ambition and greed","Legitimate government needs consent"],"The opposite of unalienable rights."),
 XM("Why did the belief that men are “ambitious, greedy, and easily corrupted” shape the Constitution?","It led the Framers to divide and check power so no one could abuse it",["It led the Framers to create a king who could restrain everyone","It made the Framers abolish the states to prevent local tyranny","It led the Framers to direct democracy so the people held all power"],"Distrust of power → separation of powers."),
 XM("If rights came from the government instead of nature, what would follow on the colonists’ logic?","Government could lawfully take them away",["Rights would become stronger","Consent would be unnecessary","Power would disappear"],"That is why they grounded rights in nature.")]);

EX("c2","Articles of Confederation",[
 XM("The Articles of Confederation were:","a weak constitution that governed America during the Revolutionary War",["the plan, offered in 1787, for a strong national government","the first ten amendments, adopted to protect individual rights","the Massachusetts constitution, with its governor’s veto"],"A weak constitution."),
 XM("The weak constitution that governed America during the Revolutionary War was the:","Articles of Confederation",["Virginia Plan of 1787","Bill of Rights of 1791","Great Compromise of 1787"],"The Articles."),
 XT("The Articles of Confederation created a strong national government the states had to obey.",false,"False — it was weak."),
 XM("How did the Articles differ from the Constitution?","The Articles made a weak national government; the Constitution a stronger one",["They were identical, except that the Constitution added a Senate","The Articles made a strong national government; the Constitution a weaker one","The Articles created the Senate; the Constitution created the House"],"The Convention replaced the weak Articles."),
 XM("A national government cannot tax or enforce its laws and must ask the states for help. Which framework is this?","The Articles of Confederation",["The Great Compromise","The Virginia Plan","The Bill of Rights"],"A confederation."),
 XM("During a crisis, the national government asks the states for money and most simply refuse. Which system’s weakness does this show?","The Articles’ confederal system",["Federalism under the Constitution","A unitary system","Separation of powers"],"States sovereign; the nation begs."),
 XM("During which war did the Articles govern America?","The Revolutionary War",["The Civil War","The War of 1812","World War I"],"From the guide."),
 XM("Which statement about the Articles is NOT true?","They created a strong executive and national courts",["They were a weak constitution for the nation","They governed America during the Revolution","They were later replaced by the Constitution"],"No strong national government."),
 XM("Why did the Articles make the national government so weak?","Having fought a king, Americans feared concentrated power",["Americans wanted a king of their own to lead them through the war","The states had no power, so the nation could not be stronger than they were","Locke opposed all government, and Americans followed his teaching"],"Distrust of power."),
 XM("Which event best exposed the Articles’ weakness and pushed toward the Convention?","Shays’s Rebellion, which the national government could not handle",["The Declaration of Independence, which the states could not agree on","The Great Compromise, which the national government could not enforce","The Bill of Rights, which the national government could not pass"],"1787, Massachusetts.")]);

EX("c2","Pennsylvania’s constitution (1776)",[
 XM("Which state constitution was the most radically democratic, giving all power to a one-house legislature?","Pennsylvania, 1776",["Massachusetts, 1780","Virginia, 1776","New Jersey, 1787"],"Pennsylvania."),
 XM("A unicameral legislature has:","one house",["two houses","three branches","no elected members"],"One house."),
 XT("Pennsylvania’s 1776 constitution gave all power to a one-house legislature.",true,"True."),
 XM("How did Pennsylvania 1776 differ from Massachusetts 1780?","Pennsylvania put all power in one house; Massachusetts separated powers",["Pennsylvania gave its governor a veto; Massachusetts had one house","Massachusetts put all power in one house; Pennsylvania separated powers","They were the same: both gave all power to a single house"],"Radical democracy vs. separation of powers."),
 XM("A state puts all power in a single elected house, with no governor’s veto and no upper chamber. Which early constitution does it resemble?","Pennsylvania’s (1776)",["Massachusetts’s (1780)","The U.S. Constitution","The Articles"],"Most radically democratic."),
 XM("A historian calls a state constitution “too democratic” because nothing checked the legislature. Which one is she most likely describing?","Pennsylvania, 1776",["Massachusetts, 1780","The Great Compromise","The New Jersey Plan"],"All power in one house."),
 XM("In what year was Pennsylvania’s radically democratic constitution adopted?","1776",["1780","1787","1791"],"1776."),
 XM("Which statement about Pennsylvania’s 1776 constitution is NOT true?","It gave its governor a strong veto",["It was the most radically democratic","It had a unicameral legislature","All power went to one house"],"That was Massachusetts."),
 XM("Why would the Framers worry about a system like Pennsylvania’s?","With no checks, a passionate majority in one house could do anything",["It had too many branches, so nothing could ever be decided","It gave judges too much power over the elected legislature","It had no elections, so the people had no voice at all"],"Unchecked power in one body."),
 XM("Given the Framers’ view of human nature, which design would they prefer to Pennsylvania’s?","Two houses, an executive veto and independent judges",["One elected house holding all power, with no veto","No legislature at all, with a council of judges instead","A hereditary king advised by an appointed council"],"Checks against ambition.")]);

EX("c2","Massachusetts’s constitution (1780)",[
 XM("The Massachusetts constitution of 1780 was a good deal less democratic. Which feature did it have?","A governor who could veto the legislature, and judges who served for life",["All power in a one-house legislature, with no veto at all","No governor at all, and judges chosen by the legislature","Judges elected every year, and a governor chosen by lot"],"A clear separation of powers."),
 XM("A clear separation of powers, a veto-wielding elected governor and life-tenured judges describe:","the Massachusetts constitution of 1780",["the Pennsylvania constitution of 1776","the Articles of Confederation","the New Jersey Plan"],"Massachusetts."),
 XT("The Massachusetts constitution of 1780 had a clear separation of powers among the branches.",true,"True."),
 XM("Compared with Pennsylvania 1776, Massachusetts 1780 was:","less democratic, with power separated and checked",["more democratic, with all power in one house","identical in design, with the same one-house legislature","a confederation, with the towns holding sovereignty"],"Separation and checks."),
 XM("A state lets its elected governor veto the legislature and gives judges life terms. Which early constitution does this resemble?","Massachusetts’s (1780)",["Pennsylvania’s (1776)","The Articles","A unitary system"],"Massachusetts."),
 XM("Why might a Framer call Massachusetts’s constitution “less democratic” and still admire it?","Its checks slowed majorities down, guarding against passion and abuse",["It abolished elections, so passion could never reach the government","It gave all power to judges, who could overrule any law at will","It restored a king, so the people no longer had to decide anything"],"Less democratic, more balanced."),
 XM("How long did judges serve under the Massachusetts constitution of 1780?","For life",["One year","Four years","Until the governor removed them"],"Life tenure."),
 XM("Which statement about Massachusetts 1780 is NOT true?","It gave all power to a one-house legislature",["It separated powers among the branches","Its governor was elected directly by voters","Its governor could veto acts of the legislature"],"That was Pennsylvania."),
 XM("Why do life terms for judges make a government less democratic?","Judges never face voters, so they can resist popular majorities",["Judges are elected more often, so they follow every shift in opinion","Judges then control taxes, so voters lose control of spending","Life terms end elections for every other office as well"],"Independence from the voters."),
 XM("Which Constitution of 1787 feature most resembles Massachusetts 1780?","A president’s veto and federal judges serving during good behavior",["A one-house Congress holding all national power","No executive at all, with Congress running everything","Direct votes by citizens on every federal law"],"The model of separated, checked powers.")]);

EX("c2","Shays’s Rebellion",[
 XM("Shays’s Rebellion (1787) was an attempt by ex-Revolutionary War soldiers to:","prevent foreclosures of farms caused by high interest rates and taxes",["overthrow the Continental Congress and install a new government","free enslaved people held on farms across New England","stop the Constitutional Convention from meeting in Philadelphia"],"Foreclosures."),
 XM("The 1787 uprising of ex-soldiers trying to stop farm foreclosures was:","Shays’s Rebellion",["the Whiskey Rebellion","the Boston Tea Party","the Great Compromise"],"Shays’s Rebellion."),
 XT("Shays’s Rebellion occurred in Pennsylvania.",false,"False — Massachusetts."),
 XM("What drove the Shays rebels, as opposed to later tax protests?","High interest rates and taxes causing farm foreclosures",["A new federal tax on whiskey distilled on farms","A state ban on slavery that ruined planters","A quarrel over how senators would be chosen"],"Debt and foreclosure."),
 XM("Indebted farmers take up arms to stop courts from seizing their land in 1787 Massachusetts. This is:","Shays’s Rebellion",["the Great Compromise","the Constitutional Convention","the Bill of Rights"],"Shays’s Rebellion."),
 XM("Leaders watching Shays’s Rebellion concluded something about their government. What?","The weak national government could not keep order",["The states were too weak to govern their own citizens","A king was needed to restore order across the nation","Farmers should rule directly through town meetings"],"It exposed the Articles."),
 XM("Who were the Shays rebels?","Ex-Revolutionary War soldiers",["British loyalists who had fled to Canada","Enslaved people escaping the southern states","Members of Congress opposed to the Articles"],"From the guide."),
 XM("Which statement about Shays’s Rebellion is NOT true?","It happened after the Constitution was ratified",["It took place in the year 1787","It took place in Massachusetts","It was about farm foreclosures and taxes"],"It came before and helped cause the Convention."),
 XM("Why did Shays’s Rebellion help lead to the Constitution?","It showed the Articles’ national government was too weak to respond",["It proved that direct democracy worked well in the states","It created the Senate by showing the need for a second house","It ended the Revolution by forcing Britain to negotiate"],"Fear of disorder."),
 XM("If the Articles’ government had possessed a strong army and tax power, what would most likely have changed about 1787?","Less urgency to replace the Articles",["More rebellions","The Declaration would be rewritten","The states would vanish"],"The weakness drove reform.")]);

EX("c2","John Locke",[
 XM("The Framers’ defense of liberty as a natural right came from the writings of:","John Locke",["Thomas Hobbes","Alexis de Tocqueville","Aristotle"],"Locke."),
 XM("John Locke was:","a 17th-century English philosopher behind the idea of liberty as a natural right",["a Framer from Virginia who proposed the plan for a strong national government","a French visitor who wrote a two-volume study of American government and life","a Greek philosopher who first defined democracy as the rule of the many"],"17th-century English."),
 XT("Locke believed an all-powerful government was necessary and that democracy was impossible.",false,"False — he believed neither."),
 XM("How did Locke differ from those who thought an all-powerful government necessary?","He thought government should be limited and democracy possible",["He wanted a king with total power, as the only guard against disorder","He opposed all government and thought people needed no rulers","He agreed with them, believing democracy was impossible"],"Limited government."),
 XM("A founder argues that people have a natural right to liberty that government exists to protect. Whose ideas is he drawing on?","John Locke’s",["Aristotle’s","Tocqueville’s","The Antifederalists’"],"Locke."),
 XM("A pamphlet says, “Government is needed, but it need not be all-powerful, and the people can govern themselves.” Whose position is this?","Locke’s",["Hobbes’s","A monarchist’s","Tocqueville’s"],"Neither all-powerful government nor impossible democracy."),
 XM("In which century did Locke write?","The 17th",["The 15th","The 18th","The 19th"],"17th-century English philosopher."),
 XM("Which statement about Locke is NOT true?","He thought democracy was impossible",["He was English","He defended liberty as a natural right","He did not think all-powerful government necessary"],"He thought it possible."),
 XM("Why did Locke’s ideas fit the colonists’ cause?","If rights are natural, a government that violates them loses its claim to obedience",["Locke favored kings, and the colonists wanted a king of their own","Locke opposed natural rights, which let the colonists invent new ones","Locke wrote the Articles, so the colonists already followed him"],"Natural rights justify resistance."),
 XM("Which pair of ideas best combines Locke with the Framers’ distrust of power?","Natural rights plus limited, divided government",["Absolute monarchy plus natural rights","Direct democracy plus no rights","A confederation plus a king"],"Protect rights by limiting power.")]);

EX("c2","Virginia Plan vs. New Jersey Plan",[
 XM("The proposal to create a strong national government was the:","Virginia Plan",["New Jersey Plan","Great Compromise","Articles of Confederation"],"Virginia."),
 XM("The New Jersey Plan proposed:","a weak national government",["a strong national government","representation by population in both houses","a king"],"Weak."),
 XT("The New Jersey Plan proposed a strong national government.",false,"False — that was the Virginia Plan."),
 XM("What separated the two plans at the Convention?","How strong the national government should be",["Whether to declare independence from Britain","Whether the nation should have any courts","Whether to abolish slavery in every state"],"Strong vs. weak."),
 XM("A small state fears being outvoted and wants a weak national government. Which plan would it favor?","The New Jersey Plan",["The Virginia Plan","The three-fifths plan","The Pennsylvania constitution"],"Weak national government."),
 XM("A large, populous state wants a strong national government that reflects its size. Which plan?","The Virginia Plan",["The New Jersey Plan","The Articles","A confederation"],"Strong national government."),
 XM("Which plan was named for the state of the delegates who proposed a weak national government?","New Jersey",["Virginia","Pennsylvania","Massachusetts"],"The New Jersey Plan."),
 XM("Which statement is NOT true?","The Virginia Plan kept the weak Articles",["The Virginia Plan wanted a strong national government","The New Jersey Plan wanted a weak one","The Great Compromise followed"],"It sought a strong national government."),
 XM("Why did small states resist the Virginia Plan?","A strong national government by population would let large states outvote them",["They wanted a king who would protect the small states from the large","They opposed any constitution and wanted to keep the colonies separate","They had more people and feared being taxed by smaller states"],"Fear of being outnumbered."),
 XM("Which outcome best shows the two plans were reconciled?","The Great Compromise: population in the House, equal Senate seats",["The Virginia Plan adopted whole: population in both houses","The New Jersey Plan adopted whole: equal votes in one house","The Articles kept unchanged, with each state holding one vote"],"Each side won one chamber.")]);

EX("c2","The Great Compromise",[
 XM("The Great Compromise created:","a House based on state population and a Senate with two members for each state",["one house in which every state had an equal vote","a Senate by population and a House with two members per state","an executive council chosen by the state legislatures"],"The Great Compromise."),
 XM("A popularly elected House based on population and a state-selected Senate with two per state is the:","Great Compromise",["Virginia Plan","New Jersey Plan","three-fifths clause"],"The Great Compromise."),
 XT("Under the Great Compromise, senators were originally selected by the states.",true,"True."),
 XM("How do the two chambers differ under the Great Compromise?","The House reflects population; the Senate gives each state two",["Both houses reflect each state’s population","Both houses give each state two members","The Senate reflects population; the House gives each state two"],"Population vs. equality of states."),
 XM("Large states wanted representation by population; small states wanted equality. How did the Great Compromise satisfy both?","Population in the House, two senators per state in the Senate",["Population in both the House and the Senate","Equal votes for each state in both houses","One house, with seats rotating among the states"],"Each got a chamber."),
 XM("Wyoming and California have very different populations but the same number of senators. Which decision explains this?","The Great Compromise",["The three-fifths clause","The New Jersey Plan alone","The Tenth Amendment"],"Two per state."),
 XM("How many senators does each state get under the Great Compromise?","Two",["One","Three","Depends on population"],"Two."),
 XM("Which statement is NOT true?","The House gives each state two members",["The House is based on population","The Senate has two per state","Senators were first chosen by the states"],"That is the Senate."),
 XM("Why was a compromise needed at all?","Large and small states each feared the other would dominate",["The Articles required a compromise before any change","The king of England insisted on a two-house Congress","Locke had demanded that every nation have a Senate"],"Big vs. small."),
 XM("If representation in both houses were by population, which states would likely have objected most?","Small states, who would lose influence",["Large states, who would gain nothing new","No state, since all would be treated alike","Only Virginia, which proposed the plan"],"The New Jersey Plan’s supporters.")]);

EX("c2","Federalism and separation of powers",[
 XM("Government authority shared by national and state governments is:","federalism",["separation of powers","enumerated powers","a unitary system"],"Federalism."),
 XM("Sharing of constitutional authority by multiple branches of government is:","separation of powers",["federalism","devolution","a confederation"],"Separation of powers."),
 XT("Federalism divides authority among the three branches of the national government.",false,"False — that is separation of powers; federalism divides it between national and state governments."),
 XM("Which pairing is correct?","Federalism: national vs. state; separation of powers: among branches",["Federalism: among branches; separation: national vs. state","They mean the same","Both mean the Senate"],"Levels vs. branches."),
 XM("The national government runs the post office; your state issues your driver’s license. This shows:","federalism",["separation of powers","legitimacy","client politics"],"Shared between levels."),
 XM("Congress passes a law, the president vetoes it, and Congress overrides. Which principle is at work?","Separation of powers",["Federalism","Devolution","A confederation"],"Branches checking each other."),
 XM("The United States separates powers among how many equal branches of its national government?","Three",["Two","Four","Five"],"Three."),
 XM("Which statement is NOT true?","Separation of powers means states share power with the nation",["Federalism shares power between the national and state levels","Separation of powers shares authority among the branches","Both principles limit how much power any one part holds"],"That is federalism."),
 XM("Why did the Framers use both federalism and separation of powers?","Dividing power twice made it harder for any one group to abuse it",["To make government faster by giving each part its own job","To end the states gradually by moving power upward","To create a king by uniting the branches under one head"],"Double security against ambition."),
 XM("If a governor ignored a national law, and a court ruled against the governor, which two principles are both in play?","Federalism (state vs. nation) and separation of powers (the court checking)",["Only federalism, because the case involves a governor and a national law","Only separation of powers, because a court is checking another official","Neither principle, because courts may never review what governors do"],"Both divisions working together.")]);

EX("c2","Enumerated powers",[
 XM("Powers given to the national government alone are:","enumerated powers",["reserved powers","conditions of aid","separation of powers"],"Enumerated."),
 XM("Enumerated powers are:","powers given to the national government alone",["powers reserved to the states by the Tenth Amendment","powers shared among the three branches of government","conditions the nation sets on money given to states"],"Listed national powers."),
 XT("Enumerated powers are the powers reserved to the states.",false,"False — national government alone."),
 XM("How do enumerated powers differ from the states’ rights of the Tenth Amendment?","Enumerated powers are listed for the nation; the Tenth reserves the rest to the states",["They are the same thing, described in two places","Enumerated powers belong to the states; the Tenth lists the nation’s","The Tenth lists national powers; enumerated powers are the states’"],"Listed vs. reserved."),
 XM("Congress coins money because the Constitution lists that power for it. This is:","an enumerated power",["devolution","a condition of aid","a reserved state power"],"Enumerated."),
 XM("Congress wants to do something no clause lists. Which clause might it stretch?","The necessary and proper clause",["The three-fifths clause","The establishment clause","The Tenth Amendment"],"Beyond the enumerated powers."),
 XM("Which is an example of an enumerated national power?","Coining money",["Issuing driver’s licenses","Running local schools","Setting marriage ages"],"Listed for Congress."),
 XM("Which statement about enumerated powers is NOT true?","They let states coin their own money",["They are given to the national government","They are listed in the Constitution","The necessary and proper clause extends them"],"National alone."),
 XM("Why did the Framers list the national government’s powers?","To limit it to specific tasks and leave the rest to states and people",["To make it unlimited by naming everything it might do","To abolish the states by moving their duties to Congress","To create a king by listing the powers of one ruler"],"A government of listed powers."),
 XM("If Congress claimed a power that is neither listed nor necessary and proper to a listed one, which argument would a state most likely make?","The Tenth Amendment reserves that power to the states",["The three-fifths clause forbids that kind of power","The establishment clause forbids that kind of power","The Great Compromise forbids that kind of power"],"States’ rights.")]);

EX("c2","Antifederalists and the Bill of Rights",[
 XM("Those who favored a weaker national government were the:","Antifederalists",["Federalists","Framers","Loyalists"],"Antifederalists."),
 XM("The Bill of Rights is:","the first ten amendments to the Constitution",["the first ten articles of the original Constitution","the Declaration of Independence and its list of grievances","the Articles of Confederation, adopted during the war"],"First ten amendments."),
 XT("The Antifederalists favored a stronger national government.",false,"False — a weaker one."),
 XM("How did Antifederalists differ from Federalists?","Antifederalists wanted a weaker national government; Federalists a stronger one",["They agreed on everything except the name of the Senate","Antifederalists wanted a king; Federalists wanted a republic","Federalists wanted the Articles; Antifederalists a strong nation"],"Weaker vs. stronger."),
 XM("A delegate fears the new national government will crush the states and individual rights. He is likely:","an Antifederalist",["a Federalist","a monarchist","a pluralist"],"Weaker national government."),
 XM("A group agrees to accept the Constitution if a list of protected rights is added. What did that demand produce?","The Bill of Rights",["The Great Compromise","The three-fifths clause","The New Jersey Plan"],"The first ten amendments."),
 XM("How many amendments make up the Bill of Rights?","Ten",["Five","Twelve","Twenty-seven"],"Ten."),
 XM("Which statement is NOT true?","The Bill of Rights is part of the original Articles",["It is the first ten amendments","Antifederalists wanted rights protected","Antifederalists favored a weaker national government"],"Amendments to the Constitution."),
 XM("Why did the Antifederalists push for a bill of rights?","A strong national government might threaten individual liberty",["They wanted a king to guarantee their rights personally","They opposed all rights and wanted to test the Federalists","They wanted the Senate abolished and used rights as leverage"],"Protection against a strong center."),
 XM("Which best describes the Antifederalists’ lasting influence?","Though they lost ratification, their demand gave us the Bill of Rights",["They won ratification and kept the Articles in force","They created the Senate as the price of their support","They wrote the Constitution after the Federalists left"],"A loss that shaped the result.")]);
