/* ---- Exam 50 · chapter 3 · seven topics, ten levels each ---- */
EX("c3","Obamacare and federalism",[
 XM("The fight over the 2010 federal health reform law (Obamacare) was in large part a battle over:","how the federal government should relate to the states",["the separation of church and state in health care","the president’s war powers during a national emergency","the right to a jury trial in cases over medical bills"],"Federalism."),
 XM("The 2010 federal health reform law is commonly called:","Obamacare",["Medicare","Social Security","The New Deal"],"Obamacare."),
 XT("The legal challenges to Obamacare were mainly about freedom of the press.",false,"False — how the federal government relates to the states."),
 XM("Obamacare’s legal fights were about federalism rather than separation of powers because:","they pitted national power against state power",["they pitted Congress against the president","they were about the courts only","they concerned religion"],"Levels, not branches."),
 XM("States sue, saying a national health law forces them to change their own programs. What kind of conflict is this?","A federalism conflict between national and state power",["A separation-of-powers conflict between Congress and the president","A civil liberties conflict over freedom of speech and the press","A dispute over reviving the Articles of Confederation"],"Federalism."),
 XM("A state refuses to expand a program under a national law, and courts must decide whether it can. Which chapter 3 theme does this illustrate?","How the federal government should relate to the states",["The rule of the many, as Aristotle defined democracy","Unalienable rights, grounded in nature and Providence","Political culture, a patterned way of thinking"],"The federalism battle."),
 XM("In what year was the federal health reform law passed?","2010",["2001","2016","1996"],"2010."),
 XM("Which statement about the Obamacare fights is NOT true?","They were about the separation of church and state",["They concerned federalism","They involved legal challenges","They concerned national–state relations"],"Not church and state."),
 XM("Why do national programs like Obamacare so often end in federalism fights?","They reach into areas the states have traditionally run",["The Constitution forbids any federal law about health","States have no powers of their own to protect","Courts ignore the states whenever Congress acts"],"Overlap breeds conflict."),
 XM("Which best predicts what happens when Washington offers states money with strings attached for a health program?","Some states accept, others resist, and courts may decide how far the strings can reach",["Every state must accept, because federal money cannot legally be refused by any state","No state can refuse, because the Tenth Amendment no longer protects the states","The Senate alone decides which states must take part, and courts stay out of it"],"Conditions of aid meet federalism.")]);

EX("c3","Gibbons v. Ogden",[
 XM("Gibbons v. Ogden (1824) held that the commerce clause gives the national government exclusive power to regulate:","interstate commerce",["immigration","elections","intrastate taxes"],"Interstate commerce."),
 XM("The 1824 case holding that the national government alone regulates interstate commerce is:","Gibbons v. Ogden",["Arizona v. United States","McCulloch v. Maryland","Marbury v. Madison"],"Gibbons."),
 XT("Gibbons v. Ogden held that each state regulates commerce between states.",false,"False — the national government, exclusively."),
 XM("How does Gibbons v. Ogden differ from Arizona v. United States?","Gibbons is about interstate commerce; Arizona about immigration",["They are the same case, decided twice","Gibbons is about immigration; Arizona about commerce","Both are about the power of states over trade"],"Commerce vs. immigration."),
 XM("A state grants one company a monopoly on steamboats running between two states. After Gibbons, who controls that trade?","The national government, under the commerce clause",["The state that granted the monopoly, since it chartered the company","Both states, jointly, through a treaty between them","The steamboat company itself, under its private charter"],"Interstate commerce."),
 XM("A state taxes trucks only when they cross into it from other states, to protect its own firms. Which ruling’s principle is at stake?","Gibbons v. Ogden — interstate commerce is the national government’s",["Arizona v. United States — immigration is the national government’s","The Tenth Amendment alone — each state controls its own borders","The Great Compromise — each state has two votes on trade"],"Commerce between states."),
 XM("Which clause of the Constitution was at the heart of Gibbons v. Ogden?","The commerce clause",["The necessary and proper clause","The establishment clause","The supremacy of the states"],"The commerce clause."),
 XM("Which statement about Gibbons v. Ogden is NOT true?","It gave states exclusive power over interstate trade",["It was decided by the Supreme Court in 1824","It concerned the Constitution’s commerce clause","It strengthened national power over trade"],"National, not state."),
 XM("Why did Gibbons v. Ogden expand national power over time?","So much economic activity crosses state lines that the commerce power reaches widely",["It abolished the states’ power to pass any law touching business or trade at all","It created a role for the Senate in approving all trade between the states","It ended every tax on goods carried from one state into another state"],"Commerce is everywhere."),
 XM("If Gibbons had gone the other way, what would most likely follow?","States could wall off trade with each other",["The national government would run all the schools","Immigration would be controlled by each state","The Senate would lose its role in lawmaking"],"A patchwork of state trade barriers.")]);

EX("c3","Arizona v. United States",[
 XT("Arizona v. United States (2012) held that only the federal government may regulate immigration laws and enforcement.",true,"True."),
 XM("According to Arizona v. United States (2012), who may regulate immigration?","Only the federal government",["Only the states","The states and the nation equally","City governments"],"Only the federal government."),
 XM("The 2012 case on state immigration enforcement is:","Arizona v. United States",["Gibbons v. Ogden","Marbury v. Madison","McCulloch v. Maryland"],"Arizona."),
 XM("Which pairing is correct?","Arizona: immigration is federal; Gibbons: interstate commerce is federal",["Arizona: commerce is federal; Gibbons: immigration is federal","Both give the states power over their own borders","Both concern the separation of church and state"],"Two areas of exclusive national power."),
 XM("A state passes its own immigration enforcement law. Which ruling says it may not?","Arizona v. United States (2012)",["Gibbons v. Ogden (1824)","The Great Compromise (1787)","The Tenth Amendment (1791)"],"Federal only."),
 XM("A governor argues her state may set its own rules on who may enter the country, citing states’ rights. Which ruling cuts against her?","Arizona v. United States",["Gibbons v. Ogden","The Great Compromise","The Articles"],"Immigration is federal."),
 XM("In what year was Arizona v. United States decided?","2012",["1824","1996","2020"],"2012."),
 XM("Which statement is NOT true?","Arizona v. United States let each state set immigration policy",["Only the federal government regulates immigration","It was decided in 2012","It limited state power"],"The opposite."),
 XM("Why is immigration treated as a national rather than a state matter?","Deciding who may enter the country affects the whole nation and its foreign relations",["States have no borders of their own, so there is nothing for them to control at all","The Constitution forbids states from existing as separate governments inside the nation","Courts simply prefer national rules because they are easier for judges to enforce"],"One nation, one border policy."),
 XM("Which best describes the balance Arizona v. United States struck?","States may not set their own immigration rules; the federal government controls",["States control immigration; the federal government only advises","Cities control immigration; states and nation stay out","Nobody controls immigration; it is left to the market"],"National supremacy in this area.")]);

EX("c3","Unitary, confederal and federal systems",[
 XM("A system where state governments are sovereign and the national government can do only what the states permit is:","a confederation (confederal system)",["a unitary system (national rule)","a federal system (shared rule)","a republic (representative rule)"],"Confederal."),
 XM("A unitary system is one where:","sovereignty is fully vested in the national government, not the states",["the states are sovereign and the nation acts only with their permission","sovereignty is shared between the national and state governments","there is no national government, only independent states"],"Unitary."),
 XT("In a federal system, the national and state governments share sovereignty.",true,"True."),
 XM("Which ordering runs from weakest to strongest national government?","Confederal, federal, unitary",["Unitary, federal, confederal","Federal, confederal, unitary","Confederal, unitary, federal"],"States sovereign → shared → national."),
 XM("The national government can abolish any local government and redraw its powers at will. Which system?","Unitary",["Federal","Confederal","Pluralist"],"All sovereignty national."),
 XM("A national government must get each state’s approval to act, and the states can ignore it. Which system — and which American example?","Confederal — the Articles of Confederation",["Federal — the Constitution of 1787","Unitary — the British system","Federal — the Articles of Confederation"],"States sovereign."),
 XM("Which system does the United States have under the Constitution?","Federal",["Unitary","Confederal","None"],"Shared sovereignty."),
 XM("Which statement is NOT true?","In a unitary system, the states are sovereign",["In a confederation, states are sovereign","In a federal system, sovereignty is shared","In a unitary system, the nation is sovereign"],"Unitary = national."),
 XM("Why did the Framers choose a federal rather than a unitary system?","They feared concentrated national power but needed more than a weak confederation",["They wanted a king, and they saw a federal system as the surest path to one","They opposed any national government at all and wanted independent states","The Articles of Confederation required a federal system before any change"],"The middle path."),
 XM("If the Tenth Amendment and the states’ own powers were erased, the U.S. would move toward which system?","Unitary",["Confederal","More federal","A direct democracy"],"All power national.")]);

EX("c3","Tenth Amendment",[
 XM("The Tenth Amendment is best known as the amendment for:","states’ rights",["free speech","bearing arms","due process"],"States’ rights."),
 XM("The amendment that reserves powers not given to the national government to the states is the:","Tenth",["First","Fifth","Fourteenth"],"The Tenth."),
 XT("The Tenth Amendment is about states’ rights.",true,"True."),
 XM("How does the Tenth Amendment relate to enumerated powers?","The nation gets its listed powers; the Tenth reserves the rest to the states",["The Tenth lists the national government’s powers one by one","The Tenth abolishes the states’ powers and moves them to Congress","They are the same thing, stated once in the text and once in the Tenth"],"Listed vs. reserved."),
 XM("A state argues that a power the Constitution never gives Washington belongs to it. Which amendment?","The Tenth",["The First","The Fourteenth","The Second"],"States’ rights."),
 XM("A state resists a federal rule on local school curricula, saying education was never given to Washington. Which argument is it making?","A Tenth Amendment, states’-rights argument",["A commerce clause argument about trade","An establishment clause argument about religion","A three-fifths argument about representation"],"Reserved powers."),
 XM("The guide’s short label for the Tenth Amendment is:","States’ rights",["Freedom of religion","Due process","Separation of powers"],"States’ rights."),
 XM("Which statement is NOT true?","The Tenth Amendment gives Congress unlimited power",["The Tenth Amendment concerns states’ rights","The Tenth Amendment reserves powers to the states","The Tenth Amendment is part of the Bill of Rights"],"The opposite."),
 XM("Why has the Tenth Amendment been weaker in practice than it sounds?","The necessary and proper and commerce clauses let Congress reach many areas",["The Tenth Amendment was quietly repealed after the Civil War ended","States never think to raise it in court when Congress acts against them","Courts cannot read what it reserves, so they refuse to enforce it at all"],"Implied powers grow."),
 XM("When the necessary and proper clause collides with the Tenth Amendment, which best states what is really being argued?","How far national power reaches before it hits the states’ reserved powers",["Whether the states should exist at all under the Constitution","Whether Congress should exist at all under the Constitution","Whether courts should exist to decide such disputes at all"],"The boundary of federalism.")]);

EX("c3","“Necessary and proper” clause",[
 XM("Which clause has let Congress exercise powers not specifically enumerated in the Constitution?","The “necessary and proper” clause",["The commerce clause","The supremacy clause","The establishment clause"],"Necessary and proper."),
 XM("The necessary and proper clause allows Congress to:","pass all laws necessary and proper to carry out its duties",["ignore the Constitution whenever a law seems useful","abolish the states when they refuse national laws","choose the president when no one wins a majority"],"Implied powers."),
 XT("The necessary and proper clause strictly limits Congress to the powers listed in the Constitution.",false,"False — it has let Congress exercise unlisted powers."),
 XM("How do implied powers differ from enumerated powers?","Enumerated are listed; implied come from the necessary and proper clause",["They are the same: both are listed in the Constitution","Implied powers are listed; enumerated powers are inferred","Enumerated powers come from the states; implied from Congress"],"Listed vs. implied."),
 XM("Congress creates a national bank, never mentioned in the Constitution, to help collect taxes and borrow. Which clause?","Necessary and proper",["The Tenth Amendment","The establishment clause","The three-fifths clause"],"Implied powers."),
 XM("Congress builds a national network of research labs to support its listed power to raise armies. Which clause justifies it?","Necessary and proper",["The commerce clause","The Tenth Amendment","The equal protection clause"],"Means to a listed end."),
 XM("The necessary and proper clause is also sometimes called the:","elastic clause",["supremacy clause","commerce clause","reserved clause"],"It stretches."),
 XM("Which statement is NOT true?","It was used to shrink national power",["It is in the Constitution","It permits unlisted powers","It connects to enumerated duties"],"It grew national power."),
 XM("Why has the necessary and proper clause mattered so much for federalism?","It lets national power grow beyond the list, pressing on the states",["It abolished the states, leaving only the nation","It created the Senate to check the House","It ended implied powers, limiting Congress to its list"],"Elastic national power."),
 XM("A critic says the clause makes the list of enumerated powers meaningless. What is the strongest reply?","The means must still connect to a listed duty",["The clause was repealed long ago","Congress has never actually used it","The states wrote it to limit Congress"],"Necessary and proper to its duties.")]);

EX("c3","Grants-in-aid, conditions of aid, devolution",[
 XM("Money given by the national government to the states is:","grants-in-aid",["conditions of aid","devolution","enumerated powers"],"Grants-in-aid."),
 XM("Conditions of aid are:","terms the national government sets that states must meet to receive certain federal funds",["money the national government gives the states to spend on programs","the transfer of power from the national government to state and local governments","powers the Tenth Amendment reserves to the states and to the people"],"The strings."),
 XT("Devolution is the transfer of power from the national government to state and local governments.",true,"True."),
 XM("Which pairing is correct?","Grants-in-aid are the money; conditions of aid are the strings",["Conditions of aid are the money; grants-in-aid are the strings","They are the same thing, just named at different times","Devolution is the money; conditions of aid return power"],"Money vs. strings."),
 XM("Washington offers states highway money only if they set the drinking age at 21. The requirement is:","a condition of aid",["a grant-in-aid","devolution","an enumerated power"],"The string."),
 XM("Congress hands welfare programs back to the states to run their own way. This is:","devolution",["a condition of aid","a unitary system","an enumerated power"],"Power flowing down."),
 XM("Which term names the money itself?","Grants-in-aid",["Conditions of aid","Devolution","Mandates"],"Grants-in-aid."),
 XM("Which statement is NOT true?","Devolution moves power from the states to Washington",["Grants-in-aid are federal money to states","Conditions of aid are terms on that money","Devolution moves power to states and localities"],"The reverse."),
 XM("Why can conditions of aid give Washington power it might not have directly?","States that want the money must accept the terms",["The Constitution requires states to obey","States have no choice about money","Courts set the terms"],"Money as leverage."),
 XM("A state rejects federal money to avoid its conditions. What does this show about federalism?","States can trade money for independence — the conditions work only if the money is wanted",["States must always accept federal money once it is offered, whatever the conditions","Washington controls every state completely through its spending power alone","Devolution is illegal, so states cannot refuse any federal money at all"],"Leverage has limits.")]);
