/* ---- Exam 50 · chapter 4 · nine topics, ten levels each ---- */
EX("c4","Political culture",[
 XM("A patterned and sustained way of thinking about how political and economic life ought to be carried out is:","political culture",["civic duty","civil society","the culture war"],"Political culture."),
 XM("Political culture means:","a patterned and sustained way of thinking about how political and economic life ought to be carried out",["the results of a single national election, taken as a sign of exactly what voters want that year","the text of the Constitution together with all of the laws that Congress has passed under it","a small group of wealthy and powerful elites who decide how political and economic life is run"],"Patterned and sustained."),
 XT("The United States separates powers among three equal branches of its national government.",true,"True — from the guide’s chapter 4 list."),
 XM("How does political culture differ from public opinion on one issue?","Culture is patterned and sustained; opinion on an issue can shift quickly",["They are the same: both are whatever people think this month","Culture changes every week; opinion on an issue lasts for generations","Opinion is written in the Constitution; culture is found in the courts"],"Lasting vs. momentary."),
 XM("Americans, generation after generation, expect individuals rather than the state to be responsible for their own success. This lasting outlook is part of their:","political culture",["enumerated powers","conditions of aid","legitimacy"],"Political culture."),
 XM("A poll shows voters angry about gas prices this month. A sociologist says this is not political culture. Why?","It is a passing reaction, not a patterned and sustained way of thinking",["Gas prices are an economic matter, never a political one","Polls cannot measure what people think about anything","Only the courts can create or change political culture"],"“Patterned and sustained.”"),
 XM("Which two words in the definition make political culture more than a mood?","Patterned and sustained",["Legal and written","Elected and appointed","Real and apparent"],"Patterned and sustained."),
 XM("Which statement is NOT true?","Political culture is set by each new election",["It is patterned","It is sustained","It concerns how political and economic life ought to be carried out"],"It lasts beyond elections."),
 XM("Why study political culture to understand American government?","Lasting shared beliefs shape which policies people accept",["Political culture replaces the Constitution when they conflict","Political culture decides court cases directly","Political culture chooses presidents without elections"],"Culture shapes what is politically possible."),
 XM("Two countries adopt nearly identical constitutions but govern very differently. Which chapter 4 idea best explains the difference?","Political culture",["Enumerated powers","The Great Compromise","Conditions of aid"],"Same rules, different ways of thinking.")]);

EX("c4","Tocqueville",[
 XM("Who wrote Democracy in America, in two volumes, examining our government, lifestyle and people?","Alexis de Tocqueville",["John Locke","James Madison","Max Weber"],"Tocqueville."),
 XM("Tocqueville’s Democracy in America examined Americans’:","government, lifestyle and people",["military campaigns only","court cases only","colonial charters only"],"Government, lifestyle and people."),
 XT("Democracy in America was published in two volumes.",true,"True."),
 XM("How does Tocqueville’s work differ from Locke’s?","Tocqueville observed American life; Locke wrote the theory of natural rights",["They wrote the same book, one in French and the other in English","Locke visited America in person; Tocqueville wrote on natural rights","Tocqueville helped write the Constitution; Locke later observed it"],"Observer vs. theorist."),
 XM("A French visitor tours America and writes a two-volume study of how Americans govern and live. Who?","Alexis de Tocqueville",["John Locke","Aristotle","Thomas Hobbes"],"Tocqueville."),
 XM("A student wants a foreign observer’s view of early American habits and institutions. Which work fits best?","Democracy in America",["The Articles of Confederation","The Second Treatise","The Federalist No. 10"],"Tocqueville’s study."),
 XM("How many volumes is Democracy in America?","Two",["One","Three","Five"],"Two."),
 XM("Which statement about Tocqueville is NOT true?","He wrote the Declaration of Independence",["He wrote Democracy in America","It had two volumes","He examined our government, lifestyle and people"],"That was Jefferson."),
 XM("Why is an outsider like Tocqueville useful for studying political culture?","An outsider notices habits that natives take for granted",["An outsider has a vote and so studies the system closely","An outsider writes American law and so knows it best","An outsider was a Framer and so remembers the founding"],"Fresh eyes."),
 XM("Which theme of chapter 4 would Tocqueville’s method of observing people best help explain?","Political culture",["Enumerated powers","The Tenth Amendment","The three-fifths clause"],"Ways of thinking seen in daily life.")]);

EX("c4","The five elements",[
 XL("five-elements"),
 XM("The element that says government officials should be accountable to the people is:","democracy",["liberty","equality","civic duty"],"Democracy."),
 XT("Individual responsibility means that, barring some disability, individuals are responsible for their own actions and well-being.",true,"True."),
 XM("How does equality as an element differ from liberty?","Equality: equal vote and equal chance; liberty: preoccupied with rights",["They are the same: both mean an equal share of wealth","Liberty means equal results; equality means freedom from rules","Equality means no rules at all; liberty means equal votes"],"Rights vs. equal standing."),
 XM("A citizen says, “Barring some disability, people should be responsible for their own actions.” Which element?","Individual responsibility",["Civic duty","Equality","Democracy"],"Individual responsibility."),
 XM("A voter says her first question about any law is whether it protects her rights. Which element is she showing?","Liberty",["Equality","Civic duty","Democracy"],"Americans are preoccupied with their rights."),
 XM("Which element means taking community affairs seriously and helping out when you can?","Civic duty",["Liberty","Equality","Individual responsibility"],"Civic duty."),
 XM("Which is NOT one of the five elements?","Prosperity",["Liberty","Civic duty","Individual responsibility"],"Liberty, equality, democracy, civic duty, individual responsibility."),
 XM("Why do these five elements matter for politics?","They set the shared expectations Americans use to judge government",["They are federal laws that every citizen must obey","They are court rulings that settled the culture war","They replace elections as the way to choose leaders"],"The core of political culture."),
 XM("A policy gives everyone an equal chance to compete but guarantees no equal outcome. Which element does it fit best?","Equality — as Americans usually understand it, equal opportunity",["Civic duty — the obligation to take part in public life","Democracy — officials accountable to the people they serve","Liberty — Americans’ preoccupation with their own rights"],"Equal vote and equal chance.")]);

EX("c4","Success and individual control",[
 XM("A majority of people in Germany, Italy and Poland think success in life is determined by:","forces outside an individual’s control",["hard work and effort alone","education and training alone","religious faith and prayer"],"Americans disagree."),
 XM("On whether success is in an individual’s control, Americans:","disagree with most Germans, Italians and Poles",["agree with most Europeans that outside forces decide","have no settled opinion on the question at all","say luck alone decides everything in life"],"Americans think it is largely in their control."),
 XT("Most Americans agree that success is determined by forces outside a person’s control.",false,"False — Americans disagree."),
 XM("How does the American view of success differ from the German, Italian and Polish majorities?","Americans see success as largely in their own control",["Americans credit outside forces more than Europeans do","They are the same: both credit forces beyond one’s control","Americans credit the government for most success"],"Control vs. outside forces."),
 XM("A survey asks whether effort or outside forces decide success. Compared with those Europeans, Americans are more likely to say:","effort — success is within a person’s control",["outside forces — success is beyond a person’s control","luck alone — success is a matter of chance","the government — success depends on its programs"],"Individual control."),
 XM("An American politician promises that anyone who works hard can get ahead. Why does this message land with American voters?","It matches their belief that success is within an individual’s control",["American voters distrust hard work as a path to success","American voters believe outside forces decide who gets ahead","The message is required by law in American campaigns"],"Cultural fit."),
 XM("Which three countries does the guide name as holding the opposite view?","Germany, Italy and Poland",["France, Spain and Britain","Canada, Mexico and Japan","Russia, China and India"],"Germany, Italy, Poland."),
 XM("Which statement is NOT true?","Americans mostly believe outside forces determine success",["Majorities in Germany, Italy and Poland credit outside forces","Americans disagree that outside forces decide success","This belief reflects America’s political culture"],"Americans disagree."),
 XM("Why would this belief make Americans wary of large welfare programs?","If success is in your control, government help seems less needed",["Americans oppose all government, whatever it does or provides","The Constitution forbids any national welfare program","Europeans pay for American welfare programs through trade"],"Culture shapes policy."),
 XM("Which element of the American system does this belief most reinforce?","Individual responsibility",["Civic duty","Democracy","A unitary system"],"Responsible for one’s own well-being.")]);

EX("c4","Civic duty",[
 XM("A belief that one has an obligation to participate in civic and political affairs is:","civic duty",["civic competence","political culture","orthodoxy"],"Civic duty."),
 XM("Civic duty means:","a belief that one has an obligation to participate in civic and political affairs",["a legal requirement to vote in every national and state election","a tax paid to the states in exchange for public services","the right to use power that comes with holding an office"],"An obligation felt."),
 XT("Civic duty is the belief that one may ignore politics as long as one obeys the law.",false,"False — it is an obligation to participate."),
 XM("How does civic duty differ from individual responsibility?","Civic duty is about serving the community; individual responsibility is about looking after yourself",["They are the same: both mean obeying the law and paying taxes","Civic duty is about looking after yourself; individual responsibility is about the community","Individual responsibility means voting; civic duty means working a steady job"],"Community vs. self."),
 XM("A woman votes and serves on a school board because she feels she ought to. Which element?","Civic duty",["Liberty","Equality","Individual responsibility"],"Civic duty."),
 XM("A man serves on jury duty only because the law makes him. Is that civic duty in the guide’s sense?","Not fully — civic duty is a felt obligation, not only legal compulsion",["Yes — any legal requirement at all counts as civic duty","No — serving on a jury is not a civic or political affair","Yes — it is really an example of individual responsibility"],"A belief one ought to participate."),
 XM("Civic duty concerns participation in which affairs?","Civic and political affairs",["Only family affairs","Only business affairs","Only religious affairs"],"Civic and political."),
 XM("Which statement is NOT true?","Civic duty means avoiding public life",["It is a felt obligation","It concerns civic and political affairs","It is one of the five elements"],"The opposite."),
 XM("Why does a democracy depend on civic duty?","Self-government works only if citizens take part",["Civic duty replaces elections in a working democracy","Judges require civic duty before hearing any case","States forbid participation beyond voting"],"Participation sustains democracy."),
 XM("If civic duty weakened across a generation, which would you most expect?","Lower voting and less community participation",["Higher voting and more community participation","Stronger churches and more charitable giving","More legitimacy and greater trust in government"],"Less felt obligation, less participation.")]);

EX("c4","Religion in American life",[
 XM("Religious people donate about how much more money to charity than secular people?","More than three times as much",["About the same amount","Twice as much","Half as much"],"More than three times."),
 XM("Compared with the average European, the average American is more likely to:","believe in God, pray daily, and acknowledge clear standards of right and wrong",["belong to an established state church and pay a church tax each year","attend church less often and hold fewer clear standards of right and wrong","reject any fixed moral standards and pray far less often than Europeans"],"From the guide."),
 XT("The average American is less likely than the average European to pray daily.",false,"False — more likely."),
 XM("How do American and European religious habits differ, by the guide?","Americans are more likely to believe in God, pray daily and hold clear moral standards",["Europeans are more likely to believe in God, pray daily and hold moral standards","They are the same in belief in God, daily prayer and clear moral standards","Americans, unlike Europeans, have an established state church and a church tax"],"More religious."),
 XM("Two neighbors earn the same income; one is religious, one secular. Who likely gives more to charity, and by how much?","The religious one — more than three times as much",["The secular one — about twice as much","About the same — income decides giving","The religious one — only slightly more"],"More than three times."),
 XM("A charity wants the most donors per dollar spent on outreach. By the guide, which group should it reach first?","Religious Americans",["Secular Americans","Europeans","Government agencies"],"They give more than three times as much."),
 XM("Which three traits does the guide list for the average American compared with Europeans?","Belief in God, daily prayer, clear standards of right and wrong",["Greater wealth, more years of education, more travel abroad","More voting, more jury service, and more taxes paid","More patriotism, more military service, and more sports"],"From the guide."),
 XM("Which statement is NOT true?","Secular people give more to charity than religious people",["Religious people give more than three times as much","Americans pray daily more than Europeans","Americans more often believe in God"],"The reverse."),
 XM("Why does religion matter to American political culture, by these notes?","It shapes moral standards and civic habits like giving and participation",["It sets tax law for churches, charities and their donors","It chooses judges through councils of church leaders","It replaces civic duty as the main public value"],"Beliefs shape public life."),
 XM("Which finding would most challenge the guide’s picture of American religion?","Americans praying and giving far less than Europeans",["Americans giving more to charity than secular Europeans","Most Americans saying they believe in God","Churches teaching members to run meetings and organize"],"It would contradict the notes.")]);

EX("c4","No established church",[
 XM("Why was religious diversity inevitable in America?","There was no established or official religion for the nation",["The Constitution required each state to support several churches","Congress funded every denomination equally from the start","Most colonists were Catholic, so other faiths had to compete"],"No established church."),
 XM("Which two groups are named for early religious friction in America?","Puritans and Catholics",["Quakers and Methodists","Baptists and Lutherans","Anglicans and Jews"],"Puritans and Catholics."),
 XT("Churches in America offered ready opportunities for developing and practicing civic and political skills.",true,"True."),
 XM("How did having no national church affect American religion, compared with nations that had one?","It made religious diversity inevitable",["It ended religion","It made one church dominant","It made religion illegal"],"Many churches."),
 XM("Why do the notes say churches mattered for democracy?","They offered opportunities to develop and practice civic and political skills",["They chose the candidates for Congress in each of the local districts","They collected taxes on behalf of the town and county governments","They wrote the new state constitutions and sent them to the voters"],"Civic training ground."),
 XM("A young woman learns to run meetings and organize volunteers at her church, then runs for city council. Which point from the guide does this illustrate?","Churches build civic and political skills",["An established religion shapes public life","Rule of the few governs local affairs","Devolution moves power to churches"],"Skills carry into politics."),
 XM("The absence of what, at the national level, made religious diversity inevitable?","An established or official religion",["A written national constitution","A Senate with two members per state","Regular national elections"],"No established church."),
 XM("Which statement is NOT true?","The nation had one official religion from the start",["Religious diversity was inevitable","Puritans and Catholics had early friction","Churches built civic skills"],"No established religion."),
 XM("Why would the absence of an established church lead to friction, as with Puritans and Catholics?","Rival faiths had to share public life with none in charge",["The law forced every faith into one national church","The king chose sides between rival churches","Churches were banned from taking part in public life"],"Diversity without a referee."),
 XM("Which judgment best links religion and democracy in the notes?","Diverse churches both caused friction and trained citizens for public life",["Religion weakened democracy entirely by dividing citizens","Only one church mattered, so diversity had no effect","Churches had no public role once there was no state church"],"Both sides of the story.")]);

EX("c4","Orthodox vs. progressive",[
 XM("The belief that morality and religion ought to be of decisive importance is:","orthodox",["progressive","libertarian","secular"],"Orthodox."),
 XM("Progressive, in the culture war, means:","a belief that personal freedom and solving social problems are more important than religion",["a belief that morality and religion ought to be of decisive importance","a belief that states’ rights come before any national policy","a belief that a few wise leaders should rule for the many"],"Progressive."),
 XT("Progressives believe morality and religion ought to be of decisive importance.",false,"False — that is the orthodox view."),
 XM("What separates the orthodox from the progressive?","Whether religion and morality, or personal freedom and social problems, come first",["Which party they vote for in national elections, and nothing deeper","Their income, since the wealthy tend to be orthodox and the poor progressive","Which region of the country they live in, north or south"],"Priorities."),
 XM("A voter says personal freedom and solving social problems matter more than religion. She is:","progressive",["orthodox","an Antifederalist","a pluralist"],"Progressive."),
 XM("A voter judges every law first by whether it is morally right by his faith. He is:","orthodox",["progressive","a confederalist","bureaucratic"],"Orthodox."),
 XM("In the orthodox view, what ought to be of decisive importance?","Morality and religion",["Personal freedom","Economic growth","States’ rights"],"Morality and religion."),
 XM("Which statement is NOT true?","Orthodox and progressive mean the same thing",["Orthodox puts morality and religion first","Progressive puts freedom and social problems first","They are two sides of the culture war"],"They are opposites."),
 XM("Why is the orthodox–progressive split called a culture war rather than an ordinary policy fight?","It is about basic values — what should matter most — not just money",["It involves armies and actual fighting between regions","It is only about taxes and who should pay them","It happens only in the courts, never among voters"],"Values, not dollars."),
 XM("A debate over a school’s moral teaching splits a town. Which prediction best fits the notes?","Orthodox residents stress moral and religious standards; progressives stress freedom and social problems",["Both sides agree on the teaching, since the question is purely a practical one","Only progressives care about it, since morality is a private matter for families","It is a federalism fight only, between the town’s school board and the state"],"The culture war lens.")]);

EX("c4","Trust in government",[
 XM("Which two events are considered huge contributors to Americans’ distrust of government?","The Vietnam War and the Watergate scandal",["World War II and the Depression","The Civil War and Reconstruction","The Cold War and the moon landing"],"Vietnam and Watergate."),
 XM("Since about when has the proportion of Americans who trust the government declined more or less steadily?","The late 1950s",["The 1920s","The late 1990s","2008"],"The late 1950s."),
 XT("Trust in the national government has risen steadily since the late 1950s.",false,"False — declined."),
 XM("How did Vietnam and Watergate damage trust in different ways?","Vietnam through a divisive war; Watergate through a presidential scandal",["Both were economic crashes that cost many people their jobs","Both were Supreme Court cases that angered many voters","Neither affected trust; both were forgotten within a year"],"War and scandal."),
 XM("A pollster finds trust in government far lower today than in 1958. Which trend from the guide does this fit?","The steady decline since the late 1950s",["A steady rise in trust since the late 1950s","No change in trust over the past sixty years","A sharp rise in trust right after Watergate"],"Declining trust."),
 XM("A historian points to a war many believed the government misled them about, and a president’s scandal. Which two events?","Vietnam and Watergate",["World War II and the Depression","The Revolution and Shays’s Rebellion","The Civil War and Reconstruction"],"Vietnam and Watergate."),
 XM("The decline in trust has been described as:","more or less steady since the late 1950s",["sudden, beginning only in 2020","limited to the 1800s and since recovered","rising every year since the 1950s"],"From the guide."),
 XM("Which statement is NOT true?","Watergate increased trust in government",["Trust has declined since the late 1950s","Vietnam contributed to distrust","Watergate contributed to distrust"],"It hurt trust."),
 XM("Why would a scandal like Watergate reduce trust in government, not just in one man?","It showed officials could abuse power and hide it",["It raised taxes on every family in the country","It ended national elections for several years","It was a fight about states’ rights and the Tenth"],"Abuse of power in office."),
 XM("If trust keeps falling, which link to earlier chapters is most at risk?","Legitimacy — authority accepted as rightful",["Enumerated powers — duties listed for Congress","The Great Compromise — the two-house Congress","The three-fifths clause — representation in the House"],"Consent and acceptance erode.")]);
